// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  LAPTOP-JOHN2
// DateTime: 24/09/2018 14:28:24
// UserName: jncro
// Input file <tml.y - 24/09/2018 14:28:19>

// options: conflicts lines gplex conflicts

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace tymake_lib
{
public enum Tokens {error=2,EOF=3,EQUALS=4,COLON=5,MUL=6,
    LPAREN=7,RPAREN=8,AMP=9,PLUS=10,MINUS=11,DOLLARS=12,
    COMMA=13,NEWLINE=14,FUNC=15,ASSIGN=16,NOT=17,NOTEQUAL=18,
    LEQUAL=19,GEQUAL=20,LBRACE=21,RBRACE=22,LBRACK=23,RBRACK=24,
    DOT=25,LT=26,GT=27,LSHIFT=28,RSHIFT=29,SEMICOLON=30,
    LOR=31,LAND=32,OR=33,AND=34,APPEND=35,ASSIGNIF=36,
    NULLCOALESCE=37,IF=38,ELSE=39,INCLUDE=40,RULEFOR=41,INPUTS=42,
    DEPENDS=43,ALWAYS=44,SHELLCMD=45,TYPROJECT=46,SOURCES=47,MKDIR=48,
    FUNCTION=49,RETURN=50,EXPORT=51,INTEGER=52,STRING=53,VOID=54,
    ARRAY=55,OBJECT=56,FUNCREF=57,ANY=58,NULL=59,FOR=60,
    FOREACH=61,IN=62,WHILE=63,DO=64,INT=65,LABEL=66};

public partial struct ValueType
#line 15 "tml.y"
       {
		public int intval;
		public string strval;
		public Statement stmtval;
		public Expression exprval;
		public List<Expression> exprlist;
		public tymake_lib.Tokens tokval;
		public Expression.EvalResult.ResultType typeval;
		public FunctionStatement.FunctionArg argval;
		public List<FunctionStatement.FunctionArg> arglistval;
		public List<Expression.EvalResult.ResultType> typelistval;
		internal List<ObjDef> objdeflist;
		internal ObjDef objdefval;
		public bool bval;
	}
#line default
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public partial class Parser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[112];
  private static State[] states = new State[198];
  private static string[] nonTerms = new string[] {
      "file", "export", "expr", "expr1p5", "expr2", "expr3", "expr4", "expr5", 
      "expr6", "expr7", "expr7a", "expr8", "expr9", "expr10", "expr11", "strlabelexpr", 
      "funccall", "labelexpr", "labelexpr2", "funcrefexpr", "stmtblock", "stmtlist", 
      "stmt", "stmt2", "define", "ifblock", "cmd", "include", "funcdef", "forblock", 
      "foreachblock", "whileblock", "doblock", "exprlist", "arrayexpr", "assignop", 
      "arg", "argtype", "arglist", "typelist", "objmember", "objlist", "objexpr", 
      "$accept", };

  static Parser() {
    states[0] = new State(new int[]{21,4,66,56,53,62,51,136,38,142,60,149,61,159,63,167,64,173,50,189,40,193,3,-2,49,-20},new int[]{-1,1,-21,3,-22,197,-23,196,-24,8,-25,9,-18,11,-19,64,-17,132,-16,133,-26,141,-30,148,-31,158,-32,166,-33,172,-2,179,-27,187,-28,191});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(-3);
    states[4] = new State(new int[]{22,195,66,56,53,62,51,136,38,142,60,149,61,159,63,167,64,173,50,189,40,193,49,-20},new int[]{-22,5,-23,196,-24,8,-25,9,-18,11,-19,64,-17,132,-16,133,-26,141,-30,148,-31,158,-32,166,-33,172,-2,179,-27,187,-28,191});
    states[5] = new State(new int[]{22,6,66,56,53,62,51,136,38,142,60,149,61,159,63,167,64,173,50,189,40,193,49,-20},new int[]{-23,7,-24,8,-25,9,-18,11,-19,64,-17,132,-16,133,-26,141,-30,148,-31,158,-32,166,-33,172,-2,179,-27,187,-28,191});
    states[6] = new State(-14);
    states[7] = new State(-17);
    states[8] = new State(-18);
    states[9] = new State(new int[]{30,10});
    states[10] = new State(-21);
    states[11] = new State(new int[]{16,129,36,130,35,131,25,-6,23,-6},new int[]{-36,12});
    states[12] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,13,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[13] = new State(-36);
    states[14] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,15,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[15] = new State(new int[]{8,16});
    states[16] = new State(-51);
    states[17] = new State(-52);
    states[18] = new State(new int[]{37,19,30,-54,8,-54,13,-54,24,-54,21,-54});
    states[19] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-4,20,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[20] = new State(-53);
    states[21] = new State(new int[]{31,22,37,-56,30,-56,8,-56,13,-56,24,-56,21,-56});
    states[22] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-5,23,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[23] = new State(-55);
    states[24] = new State(new int[]{32,25,31,-58,37,-58,30,-58,8,-58,13,-58,24,-58,21,-58});
    states[25] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-6,26,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[26] = new State(-57);
    states[27] = new State(new int[]{33,28,32,-60,31,-60,37,-60,30,-60,8,-60,13,-60,24,-60,21,-60});
    states[28] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-7,29,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[29] = new State(-59);
    states[30] = new State(new int[]{34,31,33,-62,32,-62,31,-62,37,-62,30,-62,8,-62,13,-62,24,-62,21,-62});
    states[31] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-8,32,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[32] = new State(-61);
    states[33] = new State(new int[]{4,34,18,127,34,-65,33,-65,32,-65,31,-65,37,-65,30,-65,8,-65,13,-65,24,-65,21,-65});
    states[34] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-9,35,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[35] = new State(-63);
    states[36] = new State(new int[]{26,37,27,121,19,123,20,125,4,-70,18,-70,34,-70,33,-70,32,-70,31,-70,37,-70,30,-70,8,-70,13,-70,24,-70,21,-70});
    states[37] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-10,38,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[38] = new State(-66);
    states[39] = new State(new int[]{28,40,29,119,26,-73,27,-73,19,-73,20,-73,4,-73,18,-73,34,-73,33,-73,32,-73,31,-73,37,-73,30,-73,8,-73,13,-73,24,-73,21,-73});
    states[40] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-11,41,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[41] = new State(-71);
    states[42] = new State(new int[]{10,43,11,117,28,-76,29,-76,26,-76,27,-76,19,-76,20,-76,4,-76,18,-76,34,-76,33,-76,32,-76,31,-76,37,-76,30,-76,8,-76,13,-76,24,-76,21,-76});
    states[43] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-12,44,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[44] = new State(-74);
    states[45] = new State(new int[]{6,46,10,-78,11,-78,28,-78,29,-78,26,-78,27,-78,19,-78,20,-78,4,-78,18,-78,34,-78,33,-78,32,-78,31,-78,37,-78,30,-78,8,-78,13,-78,24,-78,21,-78});
    states[46] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-13,47,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[47] = new State(-77);
    states[48] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-14,49,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[49] = new State(-79);
    states[50] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-14,51,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[51] = new State(-80);
    states[52] = new State(-81);
    states[53] = new State(new int[]{25,54,23,114,6,-82,10,-82,11,-82,28,-82,29,-82,26,-82,27,-82,19,-82,20,-82,4,-82,18,-82,34,-82,33,-82,32,-82,31,-82,37,-82,30,-82,8,-82,13,-82,24,-82,21,-82});
    states[54] = new State(new int[]{66,56},new int[]{-19,55,-17,65});
    states[55] = new State(-8);
    states[56] = new State(new int[]{7,57,16,-10,36,-10,35,-10,25,-10,23,-10,6,-10,10,-10,11,-10,28,-10,29,-10,26,-10,27,-10,19,-10,20,-10,4,-10,18,-10,34,-10,33,-10,32,-10,31,-10,37,-10,30,-10,8,-10,13,-10,24,-10,21,-10});
    states[57] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100,8,-49,13,-49},new int[]{-34,58,-3,111,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[58] = new State(new int[]{8,59,13,60});
    states[59] = new State(-12);
    states[60] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,61,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[61] = new State(-47);
    states[62] = new State(-5);
    states[63] = new State(-6);
    states[64] = new State(-7);
    states[65] = new State(-11);
    states[66] = new State(-83);
    states[67] = new State(-84);
    states[68] = new State(new int[]{16,109,7,14,17,48,11,50,53,62,66,112,65,66,23,68,57,75,49,90,59,100,24,-49,13,-49},new int[]{-34,69,-42,101,-3,111,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74,-41,113});
    states[69] = new State(new int[]{24,70,13,71});
    states[70] = new State(-93);
    states[71] = new State(new int[]{24,72,7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,61,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[72] = new State(-94);
    states[73] = new State(-85);
    states[74] = new State(-86);
    states[75] = new State(new int[]{66,76});
    states[76] = new State(new int[]{7,77});
    states[77] = new State(new int[]{52,82,53,83,55,84,56,85,54,86,49,87,58,88,8,-92,13,-92},new int[]{-40,78,-38,89});
    states[78] = new State(new int[]{8,79,13,80});
    states[79] = new State(-88);
    states[80] = new State(new int[]{52,82,53,83,55,84,56,85,54,86,49,87,58,88},new int[]{-38,81});
    states[81] = new State(-90);
    states[82] = new State(-104);
    states[83] = new State(-105);
    states[84] = new State(-106);
    states[85] = new State(-107);
    states[86] = new State(-108);
    states[87] = new State(-109);
    states[88] = new State(-110);
    states[89] = new State(-91);
    states[90] = new State(new int[]{7,91});
    states[91] = new State(new int[]{52,82,53,83,55,84,56,85,54,86,49,87,58,88,8,-97,13,-97},new int[]{-39,92,-37,99,-38,97});
    states[92] = new State(new int[]{8,93,13,95});
    states[93] = new State(new int[]{21,4},new int[]{-21,94});
    states[94] = new State(-89);
    states[95] = new State(new int[]{52,82,53,83,55,84,56,85,54,86,49,87,58,88},new int[]{-37,96,-38,97});
    states[96] = new State(-95);
    states[97] = new State(new int[]{66,98});
    states[98] = new State(-111);
    states[99] = new State(-96);
    states[100] = new State(-87);
    states[101] = new State(new int[]{24,102,13,103});
    states[102] = new State(-98);
    states[103] = new State(new int[]{24,104,66,106},new int[]{-41,105});
    states[104] = new State(-99);
    states[105] = new State(-102);
    states[106] = new State(new int[]{16,107});
    states[107] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,108,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[108] = new State(-103);
    states[109] = new State(new int[]{24,110});
    states[110] = new State(-100);
    states[111] = new State(-48);
    states[112] = new State(new int[]{7,57,16,107,25,-10,23,-10,6,-10,10,-10,11,-10,28,-10,29,-10,26,-10,27,-10,19,-10,20,-10,4,-10,18,-10,34,-10,33,-10,32,-10,31,-10,37,-10,24,-10,13,-10});
    states[113] = new State(-101);
    states[114] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,115,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[115] = new State(new int[]{24,116});
    states[116] = new State(-9);
    states[117] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-12,118,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[118] = new State(-75);
    states[119] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-11,120,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[120] = new State(-72);
    states[121] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-10,122,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[122] = new State(-67);
    states[123] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-10,124,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[124] = new State(-68);
    states[125] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-10,126,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[126] = new State(-69);
    states[127] = new State(new int[]{17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-9,128,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[128] = new State(-64);
    states[129] = new State(-37);
    states[130] = new State(-38);
    states[131] = new State(-39);
    states[132] = new State(new int[]{16,-11,36,-11,35,-11,25,-11,23,-11,30,-34});
    states[133] = new State(new int[]{25,134,23,114});
    states[134] = new State(new int[]{66,56},new int[]{-19,55,-17,135});
    states[135] = new State(new int[]{30,-35,16,-11,36,-11,35,-11,25,-11,23,-11});
    states[136] = new State(new int[]{66,139,53,62,49,-19},new int[]{-25,137,-18,11,-19,64,-17,65,-16,140});
    states[137] = new State(new int[]{30,138});
    states[138] = new State(-22);
    states[139] = new State(new int[]{7,57,30,-31,16,-10,36,-10,35,-10,25,-10,23,-10});
    states[140] = new State(new int[]{25,54,23,114});
    states[141] = new State(-23);
    states[142] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,143,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[143] = new State(new int[]{21,4},new int[]{-21,144});
    states[144] = new State(new int[]{39,145,66,-40,53,-40,51,-40,38,-40,60,-40,61,-40,63,-40,64,-40,50,-40,40,-40,49,-40,3,-40,22,-40});
    states[145] = new State(new int[]{21,4,38,142},new int[]{-21,146,-26,147});
    states[146] = new State(-41);
    states[147] = new State(-42);
    states[148] = new State(-24);
    states[149] = new State(new int[]{7,150});
    states[150] = new State(new int[]{66,56,53,62},new int[]{-25,151,-18,11,-19,64,-17,65,-16,140});
    states[151] = new State(new int[]{30,152});
    states[152] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,153,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[153] = new State(new int[]{30,154});
    states[154] = new State(new int[]{66,56,53,62},new int[]{-25,155,-18,11,-19,64,-17,65,-16,140});
    states[155] = new State(new int[]{8,156});
    states[156] = new State(new int[]{21,4},new int[]{-21,157});
    states[157] = new State(-43);
    states[158] = new State(-25);
    states[159] = new State(new int[]{7,160});
    states[160] = new State(new int[]{66,161});
    states[161] = new State(new int[]{62,162});
    states[162] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,163,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[163] = new State(new int[]{8,164});
    states[164] = new State(new int[]{21,4},new int[]{-21,165});
    states[165] = new State(-44);
    states[166] = new State(-26);
    states[167] = new State(new int[]{7,168});
    states[168] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,169,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[169] = new State(new int[]{8,170});
    states[170] = new State(new int[]{21,4},new int[]{-21,171});
    states[171] = new State(-45);
    states[172] = new State(-27);
    states[173] = new State(new int[]{21,4},new int[]{-21,174});
    states[174] = new State(new int[]{63,175});
    states[175] = new State(new int[]{7,176});
    states[176] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,177,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[177] = new State(new int[]{8,178});
    states[178] = new State(-46);
    states[179] = new State(new int[]{49,181},new int[]{-29,180});
    states[180] = new State(-28);
    states[181] = new State(new int[]{66,182});
    states[182] = new State(new int[]{7,183});
    states[183] = new State(new int[]{52,82,53,83,55,84,56,85,54,86,49,87,58,88,8,-97,13,-97},new int[]{-39,184,-37,99,-38,97});
    states[184] = new State(new int[]{8,185,13,95});
    states[185] = new State(new int[]{21,4},new int[]{-21,186});
    states[186] = new State(-13);
    states[187] = new State(new int[]{30,188});
    states[188] = new State(-29);
    states[189] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100,30,-33},new int[]{-3,190,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[190] = new State(-32);
    states[191] = new State(new int[]{30,192});
    states[192] = new State(-30);
    states[193] = new State(new int[]{7,14,17,48,11,50,53,62,66,56,65,66,23,68,57,75,49,90,59,100},new int[]{-3,194,-4,17,-5,18,-6,21,-7,24,-8,27,-9,30,-10,33,-11,36,-12,39,-13,42,-14,45,-15,52,-16,53,-18,63,-19,64,-17,65,-35,67,-43,73,-20,74});
    states[194] = new State(-50);
    states[195] = new State(-15);
    states[196] = new State(-16);
    states[197] = new State(new int[]{66,56,53,62,51,136,38,142,60,149,61,159,63,167,64,173,50,189,40,193,3,-4,49,-20},new int[]{-23,7,-24,8,-25,9,-18,11,-19,64,-17,132,-16,133,-26,141,-30,148,-31,158,-32,166,-33,172,-2,179,-27,187,-28,191});

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-44, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{});
    rules[3] = new Rule(-1, new int[]{-21});
    rules[4] = new Rule(-1, new int[]{-22});
    rules[5] = new Rule(-16, new int[]{53});
    rules[6] = new Rule(-16, new int[]{-18});
    rules[7] = new Rule(-18, new int[]{-19});
    rules[8] = new Rule(-18, new int[]{-16,25,-19});
    rules[9] = new Rule(-18, new int[]{-16,23,-3,24});
    rules[10] = new Rule(-19, new int[]{66});
    rules[11] = new Rule(-19, new int[]{-17});
    rules[12] = new Rule(-17, new int[]{66,7,-34,8});
    rules[13] = new Rule(-29, new int[]{49,66,7,-39,8,-21});
    rules[14] = new Rule(-21, new int[]{21,-22,22});
    rules[15] = new Rule(-21, new int[]{21,22});
    rules[16] = new Rule(-22, new int[]{-23});
    rules[17] = new Rule(-22, new int[]{-22,-23});
    rules[18] = new Rule(-23, new int[]{-24});
    rules[19] = new Rule(-2, new int[]{51});
    rules[20] = new Rule(-2, new int[]{});
    rules[21] = new Rule(-24, new int[]{-25,30});
    rules[22] = new Rule(-24, new int[]{51,-25,30});
    rules[23] = new Rule(-24, new int[]{-26});
    rules[24] = new Rule(-24, new int[]{-30});
    rules[25] = new Rule(-24, new int[]{-31});
    rules[26] = new Rule(-24, new int[]{-32});
    rules[27] = new Rule(-24, new int[]{-33});
    rules[28] = new Rule(-24, new int[]{-2,-29});
    rules[29] = new Rule(-24, new int[]{-27,30});
    rules[30] = new Rule(-24, new int[]{-28,30});
    rules[31] = new Rule(-27, new int[]{51,66});
    rules[32] = new Rule(-27, new int[]{50,-3});
    rules[33] = new Rule(-27, new int[]{50});
    rules[34] = new Rule(-27, new int[]{-17});
    rules[35] = new Rule(-27, new int[]{-16,25,-17});
    rules[36] = new Rule(-25, new int[]{-18,-36,-3});
    rules[37] = new Rule(-36, new int[]{16});
    rules[38] = new Rule(-36, new int[]{36});
    rules[39] = new Rule(-36, new int[]{35});
    rules[40] = new Rule(-26, new int[]{38,-3,-21});
    rules[41] = new Rule(-26, new int[]{38,-3,-21,39,-21});
    rules[42] = new Rule(-26, new int[]{38,-3,-21,39,-26});
    rules[43] = new Rule(-30, new int[]{60,7,-25,30,-3,30,-25,8,-21});
    rules[44] = new Rule(-31, new int[]{61,7,66,62,-3,8,-21});
    rules[45] = new Rule(-32, new int[]{63,7,-3,8,-21});
    rules[46] = new Rule(-33, new int[]{64,-21,63,7,-3,8});
    rules[47] = new Rule(-34, new int[]{-34,13,-3});
    rules[48] = new Rule(-34, new int[]{-3});
    rules[49] = new Rule(-34, new int[]{});
    rules[50] = new Rule(-28, new int[]{40,-3});
    rules[51] = new Rule(-3, new int[]{7,-3,8});
    rules[52] = new Rule(-3, new int[]{-4});
    rules[53] = new Rule(-4, new int[]{-5,37,-4});
    rules[54] = new Rule(-4, new int[]{-5});
    rules[55] = new Rule(-5, new int[]{-6,31,-5});
    rules[56] = new Rule(-5, new int[]{-6});
    rules[57] = new Rule(-6, new int[]{-7,32,-6});
    rules[58] = new Rule(-6, new int[]{-7});
    rules[59] = new Rule(-7, new int[]{-8,33,-7});
    rules[60] = new Rule(-7, new int[]{-8});
    rules[61] = new Rule(-8, new int[]{-9,34,-8});
    rules[62] = new Rule(-8, new int[]{-9});
    rules[63] = new Rule(-9, new int[]{-10,4,-9});
    rules[64] = new Rule(-9, new int[]{-10,18,-9});
    rules[65] = new Rule(-9, new int[]{-10});
    rules[66] = new Rule(-10, new int[]{-11,26,-10});
    rules[67] = new Rule(-10, new int[]{-11,27,-10});
    rules[68] = new Rule(-10, new int[]{-11,19,-10});
    rules[69] = new Rule(-10, new int[]{-11,20,-10});
    rules[70] = new Rule(-10, new int[]{-11});
    rules[71] = new Rule(-11, new int[]{-12,28,-11});
    rules[72] = new Rule(-11, new int[]{-12,29,-11});
    rules[73] = new Rule(-11, new int[]{-12});
    rules[74] = new Rule(-12, new int[]{-13,10,-12});
    rules[75] = new Rule(-12, new int[]{-13,11,-12});
    rules[76] = new Rule(-12, new int[]{-13});
    rules[77] = new Rule(-13, new int[]{-14,6,-13});
    rules[78] = new Rule(-13, new int[]{-14});
    rules[79] = new Rule(-14, new int[]{17,-14});
    rules[80] = new Rule(-14, new int[]{11,-14});
    rules[81] = new Rule(-14, new int[]{-15});
    rules[82] = new Rule(-15, new int[]{-16});
    rules[83] = new Rule(-15, new int[]{65});
    rules[84] = new Rule(-15, new int[]{-35});
    rules[85] = new Rule(-15, new int[]{-43});
    rules[86] = new Rule(-15, new int[]{-20});
    rules[87] = new Rule(-15, new int[]{59});
    rules[88] = new Rule(-20, new int[]{57,66,7,-40,8});
    rules[89] = new Rule(-20, new int[]{49,7,-39,8,-21});
    rules[90] = new Rule(-40, new int[]{-40,13,-38});
    rules[91] = new Rule(-40, new int[]{-38});
    rules[92] = new Rule(-40, new int[]{});
    rules[93] = new Rule(-35, new int[]{23,-34,24});
    rules[94] = new Rule(-35, new int[]{23,-34,13,24});
    rules[95] = new Rule(-39, new int[]{-39,13,-37});
    rules[96] = new Rule(-39, new int[]{-37});
    rules[97] = new Rule(-39, new int[]{});
    rules[98] = new Rule(-43, new int[]{23,-42,24});
    rules[99] = new Rule(-43, new int[]{23,-42,13,24});
    rules[100] = new Rule(-43, new int[]{23,16,24});
    rules[101] = new Rule(-42, new int[]{-41});
    rules[102] = new Rule(-42, new int[]{-42,13,-41});
    rules[103] = new Rule(-41, new int[]{66,16,-3});
    rules[104] = new Rule(-38, new int[]{52});
    rules[105] = new Rule(-38, new int[]{53});
    rules[106] = new Rule(-38, new int[]{55});
    rules[107] = new Rule(-38, new int[]{56});
    rules[108] = new Rule(-38, new int[]{54});
    rules[109] = new Rule(-38, new int[]{49});
    rules[110] = new Rule(-38, new int[]{58});
    rules[111] = new Rule(-37, new int[]{-38,66});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // file -> /* empty */
#line 48 "tml.y"
                { output = new StatementList(); }
#line default
        break;
      case 3: // file -> stmtblock
#line 49 "tml.y"
                    { output = ValueStack[ValueStack.Depth-1].stmtval; }
#line default
        break;
      case 4: // file -> stmtlist
#line 50 "tml.y"
                   { output = ValueStack[ValueStack.Depth-1].stmtval; }
#line default
        break;
      case 5: // strlabelexpr -> STRING
#line 53 "tml.y"
                           { CurrentSemanticValue.exprval = new StringExpression { val = ValueStack[ValueStack.Depth-1].strval }; }
#line default
        break;
      case 6: // strlabelexpr -> labelexpr
#line 54 "tml.y"
                    { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 7: // labelexpr -> labelexpr2
#line 57 "tml.y"
                            { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 8: // labelexpr -> strlabelexpr, DOT, labelexpr2
#line 58 "tml.y"
                                  { CurrentSemanticValue.exprval = new LabelMemberExpression { label = ValueStack[ValueStack.Depth-3].exprval, member = ValueStack[ValueStack.Depth-1].exprval }; }
#line default
        break;
      case 9: // labelexpr -> strlabelexpr, LBRACK, expr, RBRACK
#line 59 "tml.y"
                                     { CurrentSemanticValue.exprval = new LabelIndexedExpression { label = ValueStack[ValueStack.Depth-4].exprval, index = ValueStack[ValueStack.Depth-2].exprval }; }
#line default
        break;
      case 10: // labelexpr2 -> LABEL
#line 62 "tml.y"
                         { CurrentSemanticValue.exprval = new LabelExpression { val = ValueStack[ValueStack.Depth-1].strval }; }
#line default
        break;
      case 11: // labelexpr2 -> funccall
#line 63 "tml.y"
                   { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 12: // funccall -> LABEL, LPAREN, exprlist, RPAREN
#line 66 "tml.y"
                                        { CurrentSemanticValue.exprval = new FuncCall { target = ValueStack[ValueStack.Depth-4].strval, args = ValueStack[ValueStack.Depth-2].exprlist }; }
#line default
        break;
      case 13: // funcdef -> FUNCTION, LABEL, LPAREN, arglist, RPAREN, stmtblock
#line 69 "tml.y"
                                                          { CurrentSemanticValue.stmtval = new FunctionStatement { name = ValueStack[ValueStack.Depth-5].strval, args = ValueStack[ValueStack.Depth-3].arglistval, code = ValueStack[ValueStack.Depth-1].stmtval }; }
#line default
        break;
      case 14: // stmtblock -> LBRACE, stmtlist, RBRACE
#line 72 "tml.y"
                                     { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-2].stmtval; }
#line default
        break;
      case 15: // stmtblock -> LBRACE, RBRACE
#line 73 "tml.y"
                       { CurrentSemanticValue.stmtval = new StatementList(); ((StatementList)CurrentSemanticValue.stmtval).list = new List<Statement>(); }
#line default
        break;
      case 16: // stmtlist -> stmt
#line 76 "tml.y"
                      { StatementList sl = new StatementList(); sl.list = new List<Statement>(); sl.list.Add(ValueStack[ValueStack.Depth-1].stmtval); CurrentSemanticValue.stmtval = sl; }
#line default
        break;
      case 17: // stmtlist -> stmtlist, stmt
#line 77 "tml.y"
                       { ((StatementList)ValueStack[ValueStack.Depth-2].stmtval).list.Add(ValueStack[ValueStack.Depth-1].stmtval); CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-2].stmtval; }
#line default
        break;
      case 18: // stmt -> stmt2
#line 80 "tml.y"
                    { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-1].stmtval; }
#line default
        break;
      case 19: // export -> EXPORT
#line 83 "tml.y"
                       { CurrentSemanticValue.bval = true; }
#line default
        break;
      case 20: // export -> /* empty */
#line 84 "tml.y"
             { CurrentSemanticValue.bval = false; }
#line default
        break;
      case 21: // stmt2 -> define, SEMICOLON
#line 88 "tml.y"
                             { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-2].stmtval; }
#line default
        break;
      case 22: // stmt2 -> EXPORT, define, SEMICOLON
#line 89 "tml.y"
                               { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-2].stmtval; ValueStack[ValueStack.Depth-2].stmtval.export = true; }
#line default
        break;
      case 23: // stmt2 -> ifblock
#line 90 "tml.y"
                   { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-1].stmtval; }
#line default
        break;
      case 24: // stmt2 -> forblock
#line 91 "tml.y"
                   { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-1].stmtval; }
#line default
        break;
      case 25: // stmt2 -> foreachblock
#line 92 "tml.y"
                      { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-1].stmtval; }
#line default
        break;
      case 26: // stmt2 -> whileblock
#line 93 "tml.y"
                     { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-1].stmtval; }
#line default
        break;
      case 27: // stmt2 -> doblock
#line 94 "tml.y"
                   { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-1].stmtval; }
#line default
        break;
      case 28: // stmt2 -> export, funcdef
#line 95 "tml.y"
                        { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-1].stmtval; ValueStack[ValueStack.Depth-1].stmtval.export = ValueStack[ValueStack.Depth-2].bval; }
#line default
        break;
      case 29: // stmt2 -> cmd, SEMICOLON
#line 96 "tml.y"
                       { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-2].stmtval; }
#line default
        break;
      case 30: // stmt2 -> include, SEMICOLON
#line 97 "tml.y"
                          { CurrentSemanticValue.stmtval = ValueStack[ValueStack.Depth-2].stmtval; }
#line default
        break;
      case 31: // cmd -> EXPORT, LABEL
#line 100 "tml.y"
                          { CurrentSemanticValue.stmtval = new ExportStatement { v = ValueStack[ValueStack.Depth-1].strval }; }
#line default
        break;
      case 32: // cmd -> RETURN, expr
#line 101 "tml.y"
                       { CurrentSemanticValue.stmtval = new ReturnStatement { v = ValueStack[ValueStack.Depth-1].exprval }; }
#line default
        break;
      case 33: // cmd -> RETURN
#line 102 "tml.y"
                   { CurrentSemanticValue.stmtval = new ReturnStatement { v = new ResultExpression { e = new Expression.EvalResult() } }; }
#line default
        break;
      case 34: // cmd -> funccall
#line 103 "tml.y"
                    { CurrentSemanticValue.stmtval = new ExpressionStatement { expr = ValueStack[ValueStack.Depth-1].exprval }; }
#line default
        break;
      case 35: // cmd -> strlabelexpr, DOT, funccall
#line 104 "tml.y"
                                 { CurrentSemanticValue.stmtval = new ExpressionStatement { expr = new LabelMemberExpression { label = ValueStack[ValueStack.Depth-3].exprval, member = ValueStack[ValueStack.Depth-1].exprval } }; }
#line default
        break;
      case 36: // define -> labelexpr, assignop, expr
#line 107 "tml.y"
                                     { CurrentSemanticValue.stmtval = new DefineExprStatement { tok_name = ValueStack[ValueStack.Depth-3].exprval, assignop = ValueStack[ValueStack.Depth-2].tokval, val = ValueStack[ValueStack.Depth-1].exprval }; }
#line default
        break;
      case 37: // assignop -> ASSIGN
#line 110 "tml.y"
                        { CurrentSemanticValue.tokval = Tokens.ASSIGN; }
#line default
        break;
      case 38: // assignop -> ASSIGNIF
#line 111 "tml.y"
                   { CurrentSemanticValue.tokval = Tokens.ASSIGNIF; }
#line default
        break;
      case 39: // assignop -> APPEND
#line 112 "tml.y"
                  { CurrentSemanticValue.tokval = Tokens.APPEND; }
#line default
        break;
      case 40: // ifblock -> IF, expr, stmtblock
#line 115 "tml.y"
                                 { CurrentSemanticValue.stmtval = new IfBlockStatement { test = ValueStack[ValueStack.Depth-2].exprval, if_block = ValueStack[ValueStack.Depth-1].stmtval, else_block = null }; }
#line default
        break;
      case 41: // ifblock -> IF, expr, stmtblock, ELSE, stmtblock
#line 116 "tml.y"
                                      { CurrentSemanticValue.stmtval = new IfBlockStatement { test = ValueStack[ValueStack.Depth-4].exprval, if_block = ValueStack[ValueStack.Depth-3].stmtval, else_block = ValueStack[ValueStack.Depth-1].stmtval }; }
#line default
        break;
      case 42: // ifblock -> IF, expr, stmtblock, ELSE, ifblock
#line 117 "tml.y"
                                     { CurrentSemanticValue.stmtval = new IfBlockStatement { test = ValueStack[ValueStack.Depth-4].exprval, if_block = ValueStack[ValueStack.Depth-3].stmtval, else_block = ValueStack[ValueStack.Depth-1].stmtval }; }
#line default
        break;
      case 43: // forblock -> FOR, LPAREN, define, SEMICOLON, expr, SEMICOLON, define, RPAREN, 
               //             stmtblock
#line 120 "tml.y"
                                                                              { CurrentSemanticValue.stmtval = new ForBlockStatement { init = ValueStack[ValueStack.Depth-7].stmtval, test = ValueStack[ValueStack.Depth-5].exprval, incr = ValueStack[ValueStack.Depth-3].stmtval, code = ValueStack[ValueStack.Depth-1].stmtval }; }
#line default
        break;
      case 44: // foreachblock -> FOREACH, LPAREN, LABEL, IN, expr, RPAREN, stmtblock
#line 123 "tml.y"
                                                            { CurrentSemanticValue.stmtval = new ForEachBlock { val = ValueStack[ValueStack.Depth-5].strval, enumeration = ValueStack[ValueStack.Depth-3].exprval, code = ValueStack[ValueStack.Depth-1].stmtval }; }
#line default
        break;
      case 45: // whileblock -> WHILE, LPAREN, expr, RPAREN, stmtblock
#line 126 "tml.y"
                                                { CurrentSemanticValue.stmtval = new WhileBlock { test = ValueStack[ValueStack.Depth-3].exprval, code = ValueStack[ValueStack.Depth-1].stmtval }; }
#line default
        break;
      case 46: // doblock -> DO, stmtblock, WHILE, LPAREN, expr, RPAREN
#line 129 "tml.y"
                                                 { CurrentSemanticValue.stmtval = new DoBlock { test = ValueStack[ValueStack.Depth-2].exprval, code = ValueStack[ValueStack.Depth-5].stmtval }; }
#line default
        break;
      case 47: // exprlist -> exprlist, COMMA, expr
#line 132 "tml.y"
                                  { CurrentSemanticValue.exprlist = new List<Expression>(ValueStack[ValueStack.Depth-3].exprlist); CurrentSemanticValue.exprlist.Add(ValueStack[ValueStack.Depth-1].exprval); }
#line default
        break;
      case 48: // exprlist -> expr
#line 133 "tml.y"
                { CurrentSemanticValue.exprlist = new List<Expression> { ValueStack[ValueStack.Depth-1].exprval }; }
#line default
        break;
      case 49: // exprlist -> /* empty */
#line 134 "tml.y"
             { CurrentSemanticValue.exprlist = new List<Expression>(); }
#line default
        break;
      case 50: // include -> INCLUDE, expr
#line 137 "tml.y"
                            { CurrentSemanticValue.stmtval = new IncludeStatement { include_file = ValueStack[ValueStack.Depth-1].exprval }; }
#line default
        break;
      case 51: // expr -> LPAREN, expr, RPAREN
#line 140 "tml.y"
                              { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-2].exprval; }
#line default
        break;
      case 52: // expr -> expr1p5
#line 141 "tml.y"
                   { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 53: // expr1p5 -> expr2, NULLCOALESCE, expr1p5
#line 144 "tml.y"
                                       { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.NULLCOALESCE }; }
#line default
        break;
      case 54: // expr1p5 -> expr2
#line 145 "tml.y"
                 { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 55: // expr2 -> expr3, LOR, expr2
#line 148 "tml.y"
                             { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.LOR }; }
#line default
        break;
      case 56: // expr2 -> expr3
#line 149 "tml.y"
                 { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 57: // expr3 -> expr4, LAND, expr3
#line 152 "tml.y"
                             { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.LAND }; }
#line default
        break;
      case 58: // expr3 -> expr4
#line 153 "tml.y"
                 { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 59: // expr4 -> expr5, OR, expr4
#line 156 "tml.y"
                            { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.OR }; }
#line default
        break;
      case 60: // expr4 -> expr5
#line 157 "tml.y"
                 { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 61: // expr5 -> expr6, AND, expr5
#line 160 "tml.y"
                             { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.AND }; }
#line default
        break;
      case 62: // expr5 -> expr6
#line 161 "tml.y"
                 { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 63: // expr6 -> expr7, EQUALS, expr6
#line 164 "tml.y"
                               { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.EQUALS }; }
#line default
        break;
      case 64: // expr6 -> expr7, NOTEQUAL, expr6
#line 165 "tml.y"
                            { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.NOTEQUAL }; }
#line default
        break;
      case 65: // expr6 -> expr7
#line 166 "tml.y"
                 { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 66: // expr7 -> expr7a, LT, expr7
#line 169 "tml.y"
                             { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.LT }; }
#line default
        break;
      case 67: // expr7 -> expr7a, GT, expr7
#line 170 "tml.y"
                         { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.GT }; }
#line default
        break;
      case 68: // expr7 -> expr7a, LEQUAL, expr7
#line 171 "tml.y"
                            { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.LEQUAL }; }
#line default
        break;
      case 69: // expr7 -> expr7a, GEQUAL, expr7
#line 172 "tml.y"
                            { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.GEQUAL }; }
#line default
        break;
      case 70: // expr7 -> expr7a
#line 173 "tml.y"
                  { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 71: // expr7a -> expr8, LSHIFT, expr7a
#line 176 "tml.y"
                                 { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.LSHIFT }; }
#line default
        break;
      case 72: // expr7a -> expr8, RSHIFT, expr7a
#line 177 "tml.y"
                            { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.RSHIFT }; }
#line default
        break;
      case 73: // expr7a -> expr8
#line 178 "tml.y"
                 { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 74: // expr8 -> expr9, PLUS, expr8
#line 181 "tml.y"
                             { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.PLUS }; }
#line default
        break;
      case 75: // expr8 -> expr9, MINUS, expr8
#line 182 "tml.y"
                          { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.MINUS }; }
#line default
        break;
      case 76: // expr8 -> expr9
#line 183 "tml.y"
                 { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 77: // expr9 -> expr10, MUL, expr9
#line 186 "tml.y"
                             { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-3].exprval, b = ValueStack[ValueStack.Depth-1].exprval, op = Tokens.MUL }; }
#line default
        break;
      case 78: // expr9 -> expr10
#line 187 "tml.y"
                  { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 79: // expr10 -> NOT, expr10
#line 190 "tml.y"
                          { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-1].exprval, b = null, op = Tokens.NOT }; }
#line default
        break;
      case 80: // expr10 -> MINUS, expr10
#line 191 "tml.y"
                      { CurrentSemanticValue.exprval = new Expression { a = ValueStack[ValueStack.Depth-1].exprval, b = null, op = Tokens.MINUS }; }
#line default
        break;
      case 81: // expr10 -> expr11
#line 192 "tml.y"
                  { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 82: // expr11 -> strlabelexpr
#line 195 "tml.y"
                           { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 83: // expr11 -> INT
#line 196 "tml.y"
                { CurrentSemanticValue.exprval = new IntExpression { val = ValueStack[ValueStack.Depth-1].intval }; }
#line default
        break;
      case 84: // expr11 -> arrayexpr
#line 197 "tml.y"
                    { CurrentSemanticValue.exprval = new ArrayExpression { val = ValueStack[ValueStack.Depth-1].exprlist }; }
#line default
        break;
      case 85: // expr11 -> objexpr
#line 198 "tml.y"
                   { CurrentSemanticValue.exprval = new ObjExpression { val = ValueStack[ValueStack.Depth-1].objdeflist }; }
#line default
        break;
      case 86: // expr11 -> funcrefexpr
#line 199 "tml.y"
                      { CurrentSemanticValue.exprval = ValueStack[ValueStack.Depth-1].exprval; }
#line default
        break;
      case 87: // expr11 -> NULL
#line 200 "tml.y"
                { CurrentSemanticValue.exprval = new NullExpression(); }
#line default
        break;
      case 88: // funcrefexpr -> FUNCREF, LABEL, LPAREN, typelist, RPAREN
#line 203 "tml.y"
                                                   { CurrentSemanticValue.exprval = new FunctionRefExpression { name = ValueStack[ValueStack.Depth-4].strval, args = ValueStack[ValueStack.Depth-2].typelistval }; }
#line default
        break;
      case 89: // funcrefexpr -> FUNCTION, LPAREN, arglist, RPAREN, stmtblock
#line 204 "tml.y"
                                              { CurrentSemanticValue.exprval = new LambdaFunctionExpression { args = ValueStack[ValueStack.Depth-3].arglistval, code = ValueStack[ValueStack.Depth-1].stmtval }; }
#line default
        break;
      case 90: // typelist -> typelist, COMMA, argtype
#line 207 "tml.y"
                                    { CurrentSemanticValue.typelistval = new List<Expression.EvalResult.ResultType>(ValueStack[ValueStack.Depth-3].typelistval); CurrentSemanticValue.typelistval.Add(ValueStack[ValueStack.Depth-1].typeval); }
#line default
        break;
      case 91: // typelist -> argtype
#line 208 "tml.y"
                   { CurrentSemanticValue.typelistval = new List<Expression.EvalResult.ResultType>(); CurrentSemanticValue.typelistval.Add(ValueStack[ValueStack.Depth-1].typeval); }
#line default
        break;
      case 92: // typelist -> /* empty */
#line 209 "tml.y"
             { CurrentSemanticValue.typelistval = new List<Expression.EvalResult.ResultType>(); }
#line default
        break;
      case 93: // arrayexpr -> LBRACK, exprlist, RBRACK
#line 212 "tml.y"
                                     { CurrentSemanticValue.exprlist = ValueStack[ValueStack.Depth-2].exprlist; }
#line default
        break;
      case 94: // arrayexpr -> LBRACK, exprlist, COMMA, RBRACK
#line 213 "tml.y"
                                  { CurrentSemanticValue.exprlist = ValueStack[ValueStack.Depth-3].exprlist; }
#line default
        break;
      case 95: // arglist -> arglist, COMMA, arg
#line 216 "tml.y"
                                { CurrentSemanticValue.arglistval = new List<FunctionStatement.FunctionArg>(ValueStack[ValueStack.Depth-3].arglistval); CurrentSemanticValue.arglistval.Add(ValueStack[ValueStack.Depth-1].argval); }
#line default
        break;
      case 96: // arglist -> arg
#line 217 "tml.y"
                { CurrentSemanticValue.arglistval = new List<FunctionStatement.FunctionArg>(); CurrentSemanticValue.arglistval.Add(ValueStack[ValueStack.Depth-1].argval); }
#line default
        break;
      case 97: // arglist -> /* empty */
#line 218 "tml.y"
             { CurrentSemanticValue.arglistval = new List<FunctionStatement.FunctionArg>(); }
#line default
        break;
      case 98: // objexpr -> LBRACK, objlist, RBRACK
#line 221 "tml.y"
                                   { CurrentSemanticValue.objdeflist = ValueStack[ValueStack.Depth-2].objdeflist; }
#line default
        break;
      case 99: // objexpr -> LBRACK, objlist, COMMA, RBRACK
#line 222 "tml.y"
                                  { CurrentSemanticValue.objdeflist = ValueStack[ValueStack.Depth-3].objdeflist; }
#line default
        break;
      case 100: // objexpr -> LBRACK, ASSIGN, RBRACK
#line 223 "tml.y"
                             { CurrentSemanticValue.objdeflist = new List<ObjDef>(); }
#line default
        break;
      case 101: // objlist -> objmember
#line 226 "tml.y"
                          { CurrentSemanticValue.objdeflist = new List<ObjDef> { ValueStack[ValueStack.Depth-1].objdefval }; }
#line default
        break;
      case 102: // objlist -> objlist, COMMA, objmember
#line 227 "tml.y"
                               { ValueStack[ValueStack.Depth-3].objdeflist.Add(ValueStack[ValueStack.Depth-1].objdefval); CurrentSemanticValue.objdeflist = ValueStack[ValueStack.Depth-3].objdeflist; }
#line default
        break;
      case 103: // objmember -> LABEL, ASSIGN, expr
#line 230 "tml.y"
                                 { CurrentSemanticValue.objdefval = new ObjDef { name = ValueStack[ValueStack.Depth-3].strval, val = ValueStack[ValueStack.Depth-1].exprval }; }
#line default
        break;
      case 104: // argtype -> INTEGER
#line 234 "tml.y"
                         { CurrentSemanticValue.typeval = Expression.EvalResult.ResultType.Int; }
#line default
        break;
      case 105: // argtype -> STRING
#line 235 "tml.y"
                  { CurrentSemanticValue.typeval = Expression.EvalResult.ResultType.String; }
#line default
        break;
      case 106: // argtype -> ARRAY
#line 236 "tml.y"
                 { CurrentSemanticValue.typeval = Expression.EvalResult.ResultType.Array; }
#line default
        break;
      case 107: // argtype -> OBJECT
#line 237 "tml.y"
                  { CurrentSemanticValue.typeval = Expression.EvalResult.ResultType.Object; }
#line default
        break;
      case 108: // argtype -> VOID
#line 238 "tml.y"
                { CurrentSemanticValue.typeval = Expression.EvalResult.ResultType.Void; }
#line default
        break;
      case 109: // argtype -> FUNCTION
#line 239 "tml.y"
                   { CurrentSemanticValue.typeval = Expression.EvalResult.ResultType.Function; }
#line default
        break;
      case 110: // argtype -> ANY
#line 240 "tml.y"
                { CurrentSemanticValue.typeval = Expression.EvalResult.ResultType.Any; }
#line default
        break;
      case 111: // arg -> argtype, LABEL
#line 243 "tml.y"
                          { CurrentSemanticValue.argval = new FunctionStatement.FunctionArg { name = ValueStack[ValueStack.Depth-1].strval, argtype = ValueStack[ValueStack.Depth-2].typeval }; }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 247 "tml.y"

internal Statement output;
#line default
}
}
